services:

  postgres:
    image: postgres:16
    container_name: jwt-postgres

    environment:
      POSTGRES_DB: jwt_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped


  springboot:
    build: .
    container_name: jwt-springboot

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jwt_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Nikunj@123

    depends_on:
      - postgres

    restart: unless-stopped


volumes:
  postgres_data: