spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=postgres
spring.datasource.password=Nikunj@123
app.datasource.auto-create-database=false
spring.sql.init.mode=always
mybatis.configuration.map-underscore-to-camel-case=true
jwt.secret=mission-control-shared-secret-key-32-bytes-minimum